# Generated by Django 5.2 on 2025-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_published",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=15, verbose_name="цена за покупку"),
        ),
    ]
